package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Coach;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CoachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int insert(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    Coach selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    List<Coach> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int updateByPrimaryKey(Coach record);
}