package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Horse;
import org.mybatis.cdi.Mapper;

@Mapper
public interface HorseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HORSE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HORSE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int insert(Horse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HORSE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    Horse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HORSE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    List<Horse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HORSE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int updateByPrimaryKey(Horse record);
}