package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Stable;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int insert(Stable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    Stable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    List<Stable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    int updateByPrimaryKey(Stable record);
}