package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Stable;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int insert(Stable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    Stable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    List<Stable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STABLE
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    int updateByPrimaryKey(Stable record);
}