package lt.vu.mybatis.model;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COACH.ID
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COACH.PERSONAL_ID_NO
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    private Integer personalIdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COACH.NAME
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COACH.ID
     *
     * @return the value of PUBLIC.COACH.ID
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COACH.ID
     *
     * @param id the value for PUBLIC.COACH.ID
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COACH.PERSONAL_ID_NO
     *
     * @return the value of PUBLIC.COACH.PERSONAL_ID_NO
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public Integer getPersonalIdNo() {
        return personalIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COACH.PERSONAL_ID_NO
     *
     * @param personalIdNo the value for PUBLIC.COACH.PERSONAL_ID_NO
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public void setPersonalIdNo(Integer personalIdNo) {
        this.personalIdNo = personalIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COACH.NAME
     *
     * @return the value of PUBLIC.COACH.NAME
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COACH.NAME
     *
     * @param name the value for PUBLIC.COACH.NAME
     *
     * @mbg.generated Tue May 04 03:06:38 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}