package lt.vu.mybatis.model;

public class Horse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HORSE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HORSE.IDENTITY_NO
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private Integer identityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HORSE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HORSE.STABLE_ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private Long stableId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HORSE.ID
     *
     * @return the value of PUBLIC.HORSE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HORSE.ID
     *
     * @param id the value for PUBLIC.HORSE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HORSE.IDENTITY_NO
     *
     * @return the value of PUBLIC.HORSE.IDENTITY_NO
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public Integer getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HORSE.IDENTITY_NO
     *
     * @param identityNo the value for PUBLIC.HORSE.IDENTITY_NO
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setIdentityNo(Integer identityNo) {
        this.identityNo = identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HORSE.NAME
     *
     * @return the value of PUBLIC.HORSE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HORSE.NAME
     *
     * @param name the value for PUBLIC.HORSE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HORSE.STABLE_ID
     *
     * @return the value of PUBLIC.HORSE.STABLE_ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public Long getStableId() {
        return stableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HORSE.STABLE_ID
     *
     * @param stableId the value for PUBLIC.HORSE.STABLE_ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setStableId(Long stableId) {
        this.stableId = stableId;
    }
}