package lt.vu.mybatis.model;

public class Stable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STABLE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STABLE.ADDRESS
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STABLE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STABLE.ID
     *
     * @return the value of PUBLIC.STABLE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STABLE.ID
     *
     * @param id the value for PUBLIC.STABLE.ID
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STABLE.ADDRESS
     *
     * @return the value of PUBLIC.STABLE.ADDRESS
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STABLE.ADDRESS
     *
     * @param address the value for PUBLIC.STABLE.ADDRESS
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STABLE.NAME
     *
     * @return the value of PUBLIC.STABLE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STABLE.NAME
     *
     * @param name the value for PUBLIC.STABLE.NAME
     *
     * @mbg.generated Thu May 13 23:13:40 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}